Code from Wes McKinney book "Python for Data Analysis"  
Ch.4 NumPy

In [ ]:
#INFX574 W1 R1 McKinney ch.4 NumPy
import numpy as np

In [2]:
data = np.array([[ 0.9526, -0.246 , -0.8856],
[ 0.5639, 0.2379, 0.9104]])
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [3]:
data*data

array([[0.90744676, 0.060516  , 0.78428736],
       [0.31798321, 0.05659641, 0.82882816]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [6]:
#creating arrays
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
arr1.ndim

1

In [8]:
arr1.shape

(5,)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
#other ways to create arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((2, 3, 2))

array([[[8.e-323, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]],

       [[0.e+000, 0.e+000],
        [0.e+000, 0.e+000],
        [0.e+000, 0.e+000]]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr1 = np.array([1, 2, 3, 4], dtype=np.float64)
arr1

array([1., 2., 3., 4.])

In [15]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [16]:
#cast type
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [17]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [18]:
#indexing and slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr[5:8] = 12
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [20]:
arr_slice[1]

12

In [21]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [22]:
#multidim array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [23]:
arr2d[0, 2]

3

In [24]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] 

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
#slicing
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [29]:
#stopped in middle of arrays